/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lojaInformatica.projeto_integrador;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author skaio
 */
public class TelaProdutos extends javax.swing.JFrame {

    /**
     * Creates new form TelaProdutos
     */
    public TelaProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTelaProdutos = new javax.swing.JPanel();
        lblDescricao = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblCodigoProduto = new javax.swing.JLabel();
        txtCodigoProduto = new javax.swing.JTextField();
        lblCategoriaProduto = new javax.swing.JLabel();
        cboxCategoriaProduto = new javax.swing.JComboBox<>();
        lblMarcaProduto = new javax.swing.JLabel();
        cboxMarcaProduto = new javax.swing.JComboBox<>();
        lblUnidadeProduto = new javax.swing.JLabel();
        lblSubcategoriaProduto = new javax.swing.JLabel();
        cboxSubcategoriaProduto = new javax.swing.JComboBox<>();
        lblFornecedorProduto = new javax.swing.JLabel();
        cboxFornecedorProduto = new javax.swing.JComboBox<>();
        lblObservacaoProduto = new javax.swing.JLabel();
        txtObservacaoProduto = new javax.swing.JTextField();
        cboxUnidadeProduto = new javax.swing.JComboBox<>();
        lblCodigoProduto1 = new javax.swing.JLabel();
        txtReferenciaProduto = new javax.swing.JTextField();
        txtCodigofornecedorProduto = new javax.swing.JTextField();
        lblCodigoFornecedorProduto = new javax.swing.JLabel();
        lblMotivoProduto = new javax.swing.JLabel();
        cboxMotivoProduto = new javax.swing.JComboBox<>();
        txtDescricaoReduzida = new javax.swing.JTextField();
        lblDescricaoReduzida = new javax.swing.JLabel();
        txtValorProduto = new javax.swing.JTextField();
        lblValorProduto = new javax.swing.JLabel();
        txtCodigoProduto4 = new javax.swing.JTextField();
        lblQuantidadeProduto = new javax.swing.JLabel();
        lblInclusaoProduto = new javax.swing.JLabel();
        lblLoteProduto = new javax.swing.JLabel();
        txtLoteProduto = new javax.swing.JTextField();
        jftxtInclusaoProduto = new javax.swing.JFormattedTextField();
        lblValidadeProduto = new javax.swing.JLabel();
        jftxtValidadeProduto = new javax.swing.JFormattedTextField();
        pnlBotoes = new javax.swing.JPanel();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblSnProduto = new javax.swing.JLabel();
        txtSnProduto = new javax.swing.JTextField();
        lblCorProduto = new javax.swing.JLabel();
        txtCorProduto = new javax.swing.JTextField();
        lblValorProduto1 = new javax.swing.JLabel();
        cboxCondicaoProduto = new javax.swing.JComboBox<>();
        txtModeloProduto = new javax.swing.JTextField();
        lblModeloProduto = new javax.swing.JLabel();
        cboxPersonalizadoProduto = new javax.swing.JComboBox<>();
        lblPersonalizadoProduto = new javax.swing.JLabel();
        rbtnEstoqueFisico = new javax.swing.JRadioButton();
        rbtnEstoqueDigital = new javax.swing.JRadioButton();
        cboxOrigemProduto = new javax.swing.JComboBox<>();
        lblOrigemProduto = new javax.swing.JLabel();
        lblPesoProduto = new javax.swing.JLabel();
        txtCodigoProduto3 = new javax.swing.JTextField();
        lblCodigoProduto5 = new javax.swing.JLabel();
        txtCodigoProduto5 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lblGarantiaProduto = new javax.swing.JLabel();
        cboxGarantiaProduto = new javax.swing.JComboBox<>();
        lblInicioGarantiaProduto = new javax.swing.JLabel();
        lblFimGarantiaProduto = new javax.swing.JLabel();
        jftxtInicioGarantiaProduto = new javax.swing.JFormattedTextField();
        jftxtFimGarantiaProduto = new javax.swing.JFormattedTextField();
        lblDuracaoGarantiaProduto = new javax.swing.JLabel();
        txtDuracaoGarantiaProduto = new javax.swing.JTextField();
        lblValorProduto3 = new javax.swing.JLabel();
        cboxCondicaoProduto2 = new javax.swing.JComboBox<>();
        lblContatoGarantiaProduto = new javax.swing.JLabel();
        txtContatoGarantiaProduto = new javax.swing.JTextField();
        lblObservacaoGarantiaProduto = new javax.swing.JLabel();
        txtObservacaoGarantiaProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlBotoes1 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        setBackground(new java.awt.Color(204, 204, 204));

        pnlTelaProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        pnlTelaProdutos.setForeground(new java.awt.Color(204, 204, 204));
        pnlTelaProdutos.setToolTipText("");

        lblDescricao.setText("Descrição:  ");

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        lblCodigoProduto.setText("Código (SKU):");

        txtCodigoProduto.setColumns(5);
        txtCodigoProduto.setToolTipText("");
        txtCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProdutoActionPerformed(evt);
            }
        });

        lblCategoriaProduto.setText("Categoria: ");

        cboxCategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Acessórios Smartphone", "Armazenamento", "Cabos", "Conectividade", "Energia", "Hardware Mac", "Hardware PC", "Impressoras e Suprimentos", "Linha Gamer", "Monitores", "Periféricos", "Serviços/Reparos" }));

        lblMarcaProduto.setText("Marca: ");

        cboxMarcaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Acer", "Adobe", "Alienware", "AMD", "Apple", "Asus", "Cisco", "Corsair", "Dell", "Epson", "Gigabyte", "HP (Hewlett-Packard)", "Huawei", "IBM", "Intel", "Kingston", "Lenovo", "LG", "Logitech", "Microsoft", "MSI (Micro-Star International)", "Nvidia", "Panasonic", "Razer", "Samsung", "SanDisk", "Seagate", "Sony", "Toshiba", "Western Digital (WD)" }));

        lblUnidadeProduto.setText("Unidade utilizada na venda: ");

        lblSubcategoriaProduto.setText("Sub-categoria:");

        cboxSubcategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Acessórios Smartphone", "Armazenamento", "Cabos", "Conectividade", "Energia", "Hardware Mac", "Hardware PC", "Impressoras e Suprimentos", "Linha Gamer", "Monitores", "Periféricos", "Serviços/Reparos" }));

        lblFornecedorProduto.setText("Fornecedor:");

        cboxFornecedorProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Fornecedor 1", "Fornecedor 2", "Fornecedor 3", "Fornecedor 4", "Fornecedor 5", "Fornecedor 6", "Fornecedor 7" }));

        lblObservacaoProduto.setText("Observação/Detalhamento:");

        cboxUnidadeProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Litros", "Quilograma (KG)", "Metros (m)", "Metro Quadrado (m²)", "Unidade" }));

        lblCodigoProduto1.setText("Referência:");

        txtReferenciaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReferenciaProdutoActionPerformed(evt);
            }
        });

        lblCodigoFornecedorProduto.setText("Código do Fornecedor:");

        lblMotivoProduto.setText("Motivo Inclusão: ");

        cboxMotivoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Compra", "Devolução", " " }));

        lblDescricaoReduzida.setText("Descrição reduzida:  ");

        lblValorProduto.setText("Valor Unitário: ");

        lblQuantidadeProduto.setText("Quantidade:");

        lblInclusaoProduto.setText("Data de inclusão:");

        lblLoteProduto.setText("Lote:");

        jftxtInclusaoProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lblValidadeProduto.setText("Validade:");

        jftxtValidadeProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout pnlTelaProdutosLayout = new javax.swing.GroupLayout(pnlTelaProdutos);
        pnlTelaProdutos.setLayout(pnlTelaProdutosLayout);
        pnlTelaProdutosLayout.setHorizontalGroup(
            pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCodigoProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(txtCodigoProduto, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(56, 56, 56)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoProduto1)
                            .addComponent(txtReferenciaProduto))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricao)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescricaoReduzida)
                            .addComponent(txtDescricaoReduzida, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigofornecedorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategoriaProduto))
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTelaProdutosLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxSubcategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubcategoriaProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                        .addComponent(lblMarcaProduto)
                                        .addGap(528, 528, 528))
                                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                        .addComponent(cboxMarcaProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(266, 266, 266))))
                            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(cboxFornecedorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnidadeProduto)
                                    .addComponent(cboxUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblQuantidadeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCodigoProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorProduto)
                                    .addComponent(lblValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jftxtInclusaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblInclusaoProduto, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(20, 20, 20))))
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblObservacaoProduto)
                            .addComponent(txtObservacaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblMotivoProduto))
                            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboxMotivoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftxtValidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblValidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                .addComponent(lblLoteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLoteProduto))
                        .addContainerGap())
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                .addComponent(lblCodigoFornecedorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFornecedorProduto)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlTelaProdutosLayout.setVerticalGroup(
            pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addComponent(lblDescricaoReduzida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricaoReduzida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addComponent(lblCodigoProduto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtReferenciaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addComponent(lblCodigoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaProdutosLayout.createSequentialGroup()
                        .addComponent(lblCategoriaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaProdutosLayout.createSequentialGroup()
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMarcaProduto)
                            .addComponent(lblSubcategoriaProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxSubcategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaProdutosLayout.createSequentialGroup()
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCodigoFornecedorProduto)
                                    .addComponent(lblFornecedorProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboxFornecedorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigofornecedorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTelaProdutosLayout.createSequentialGroup()
                                .addComponent(lblUnidadeProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                .addComponent(lblQuantidadeProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoProduto4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                    .addComponent(lblValorProduto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                                    .addComponent(lblInclusaoProduto)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jftxtInclusaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addComponent(lblObservacaoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtObservacaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTelaProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                            .addComponent(lblMotivoProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cboxMotivoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlTelaProdutosLayout.createSequentialGroup()
                            .addComponent(lblLoteProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtLoteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTelaProdutosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jftxtValidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblValidadeProduto))
                .addContainerGap())
        );

        pnlBotoes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBotoes.setForeground(new java.awt.Color(153, 153, 153));

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(150, 150, 150)
                .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addGap(225, 225, 225))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Características do Produto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        lblSnProduto.setText("S/N:");

        lblCorProduto.setText("Cor/Variação");

        lblValorProduto1.setText("Condição: ");

        cboxCondicaoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "Novo", "Usado", "Recondicionado" }));

        txtModeloProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloProdutoActionPerformed(evt);
            }
        });

        lblModeloProduto.setText("Modelo:");

        cboxPersonalizadoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "SIM", "NÃO", " " }));

        lblPersonalizadoProduto.setText("Produto Personalizado?");

        rbtnEstoqueFisico.setText("Estoque Físico");
        rbtnEstoqueFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEstoqueFisicoActionPerformed(evt);
            }
        });

        rbtnEstoqueDigital.setText("Estoque Digital");

        cboxOrigemProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "NACIONAL", "IMPORTADO", " " }));

        lblOrigemProduto.setText("Origem:");

        lblPesoProduto.setText("Peso (Kg):");

        lblCodigoProduto5.setText("Dimensões (cm):");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSnProduto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorProduto)
                            .addComponent(txtCorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cboxCondicaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnEstoqueDigital)
                    .addComponent(rbtnEstoqueFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxPersonalizadoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPersonalizadoProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoProduto3)
                            .addComponent(lblPesoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblModeloProduto)
                    .addComponent(txtModeloProduto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxOrigemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrigemProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCodigoProduto5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCodigoProduto5)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModeloProduto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSnProduto)
                        .addComponent(lblCorProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModeloProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblValorProduto1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxCondicaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOrigemProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxOrigemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(rbtnEstoqueFisico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnEstoqueDigital))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCodigoProduto5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoProduto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPersonalizadoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboxPersonalizadoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPesoProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoProduto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informações de Garantia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        lblGarantiaProduto.setText("Garantia: ");

        cboxGarantiaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "PADRÃO/FABRICANTE", "ESTENDIDA", "SEM GARANTIA" }));

        lblInicioGarantiaProduto.setText("Data Início:");

        lblFimGarantiaProduto.setText("Data Fim:");

        jftxtInicioGarantiaProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jftxtFimGarantiaProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lblDuracaoGarantiaProduto.setText("Duração (meses):");

        lblValorProduto3.setText("Cobertura:");

        cboxCondicaoProduto2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<SELECIONE>", "DEFEITO DE FABRICAÇÃO", "SATISFAÇÃO", "REPARO/PEÇAS", "ESTENDIDA", "N/A", " ", " " }));

        lblContatoGarantiaProduto.setText("Contato de Suporte p/ Garantia:");

        lblObservacaoGarantiaProduto.setText("Observação/Detalhamento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtObservacaoGarantiaProduto)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblGarantiaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                    .addComponent(cboxGarantiaProduto, 0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblValorProduto3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboxCondicaoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(35, 35, 35)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jftxtInicioGarantiaProduto)
                                        .addComponent(lblInicioGarantiaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jftxtFimGarantiaProduto)
                                        .addComponent(lblFimGarantiaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblDuracaoGarantiaProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDuracaoGarantiaProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblContatoGarantiaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtContatoGarantiaProduto)))
                        .addComponent(lblObservacaoGarantiaProduto)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDuracaoGarantiaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDuracaoGarantiaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblInicioGarantiaProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftxtInicioGarantiaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblFimGarantiaProduto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jftxtFimGarantiaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblGarantiaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxGarantiaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblValorProduto3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxCondicaoProduto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblContatoGarantiaProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContatoGarantiaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservacaoGarantiaProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtObservacaoGarantiaProduto)
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código (SKU)", "Descrição", "Categoria", "Marca", "Quantidade", "Valor Unitário", "Dt. de Inclusão", "Condição", "Estoque", "Lote"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pnlBotoes1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBotoes1.setForeground(new java.awt.Color(153, 153, 153));

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoes1Layout = new javax.swing.GroupLayout(pnlBotoes1);
        pnlBotoes1.setLayout(pnlBotoes1Layout);
        pnlBotoes1Layout.setHorizontalGroup(
            pnlBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoes1Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(150, 150, 150)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(298, 298, 298))
        );
        pnlBotoes1Layout.setVerticalGroup(
            pnlBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlTelaProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlTelaProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotoes1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloProdutoActionPerformed

    private void txtCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProdutoActionPerformed


    }//GEN-LAST:event_txtCodigoProdutoActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // adicionando as validações quando clicar no botão 'adicinar'. 

        if (txtCodigoProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo 'Codigo SKU' precisa ser preenchido");
            txtCodigoProduto.requestFocusInWindow();
           
        } else {
          
            return;
        }

        if (txtReferenciaProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo 'Referência' precisa ser preenchido");
            txtReferenciaProduto.requestFocusInWindow();
         
        } else {
        
           
            return;
        }

        if (txtDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "O campo 'Descrição' precisa ser preenchido");
            txtDescricao.requestFocusInWindow();
        
        } else {
          
            return;
        }

        if (cboxCategoriaProduto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione uma categoria!");
            cboxCategoriaProduto.requestFocusInWindow();
          
        } else {
          
            return;
        }
        if (cboxMarcaProduto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione uma Marca!");
            cboxMarcaProduto.requestFocusInWindow();
          
        } else {
          
            return;
        }
        if (txtValorProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor informe o valor unitário!");
            txtValorProduto.requestFocusInWindow();
       
        } else {
        
            return;
        }

        if (jftxtInclusaoProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Por favor informe a data de inclusão do produto!");
            jftxtInclusaoProduto.requestFocusInWindow();
         
        }else { 
         
            return;
        }
        
        if(cboxCondicaoProduto.getSelectedIndex()== 0){
            JOptionPane.showMessageDialog(rootPane, "Por favor selecione a condição do produto!");
            cboxCondicaoProduto.requestFocusInWindow();
    
        }else{ 
       
            return;
        }
        
  // Adicionar abaixo o restante das validações  
      
        btnCancelar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAdicionar.setEnabled(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void txtReferenciaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReferenciaProdutoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtReferenciaProdutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        btnCancelar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnAdicionar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        btnCancelar.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAdicionar.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        btnCancelar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(true);
        btnAdicionar.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void rbtnEstoqueFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEstoqueFisicoActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_rbtnEstoqueFisicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JComboBox<String> cboxCategoriaProduto;
    private javax.swing.JComboBox<String> cboxCondicaoProduto;
    private javax.swing.JComboBox<String> cboxCondicaoProduto2;
    private javax.swing.JComboBox<String> cboxFornecedorProduto;
    private javax.swing.JComboBox<String> cboxGarantiaProduto;
    private javax.swing.JComboBox<String> cboxMarcaProduto;
    private javax.swing.JComboBox<String> cboxMotivoProduto;
    private javax.swing.JComboBox<String> cboxOrigemProduto;
    private javax.swing.JComboBox<String> cboxPersonalizadoProduto;
    private javax.swing.JComboBox<String> cboxSubcategoriaProduto;
    private javax.swing.JComboBox<String> cboxUnidadeProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField jftxtFimGarantiaProduto;
    private javax.swing.JFormattedTextField jftxtInclusaoProduto;
    private javax.swing.JFormattedTextField jftxtInicioGarantiaProduto;
    private javax.swing.JFormattedTextField jftxtValidadeProduto;
    private javax.swing.JLabel lblCategoriaProduto;
    private javax.swing.JLabel lblCodigoFornecedorProduto;
    private javax.swing.JLabel lblCodigoProduto;
    private javax.swing.JLabel lblCodigoProduto1;
    private javax.swing.JLabel lblCodigoProduto5;
    private javax.swing.JLabel lblContatoGarantiaProduto;
    private javax.swing.JLabel lblCorProduto;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblDescricaoReduzida;
    private javax.swing.JLabel lblDuracaoGarantiaProduto;
    private javax.swing.JLabel lblFimGarantiaProduto;
    private javax.swing.JLabel lblFornecedorProduto;
    private javax.swing.JLabel lblGarantiaProduto;
    private javax.swing.JLabel lblInclusaoProduto;
    private javax.swing.JLabel lblInicioGarantiaProduto;
    private javax.swing.JLabel lblLoteProduto;
    private javax.swing.JLabel lblMarcaProduto;
    private javax.swing.JLabel lblModeloProduto;
    private javax.swing.JLabel lblMotivoProduto;
    private javax.swing.JLabel lblObservacaoGarantiaProduto;
    private javax.swing.JLabel lblObservacaoProduto;
    private javax.swing.JLabel lblOrigemProduto;
    private javax.swing.JLabel lblPersonalizadoProduto;
    private javax.swing.JLabel lblPesoProduto;
    private javax.swing.JLabel lblQuantidadeProduto;
    private javax.swing.JLabel lblSnProduto;
    private javax.swing.JLabel lblSubcategoriaProduto;
    private javax.swing.JLabel lblUnidadeProduto;
    private javax.swing.JLabel lblValidadeProduto;
    private javax.swing.JLabel lblValorProduto;
    private javax.swing.JLabel lblValorProduto1;
    private javax.swing.JLabel lblValorProduto3;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlBotoes1;
    private javax.swing.JPanel pnlTelaProdutos;
    private javax.swing.JRadioButton rbtnEstoqueDigital;
    private javax.swing.JRadioButton rbtnEstoqueFisico;
    private javax.swing.JTextField txtCodigoProduto;
    private javax.swing.JTextField txtCodigoProduto3;
    private javax.swing.JTextField txtCodigoProduto4;
    private javax.swing.JTextField txtCodigoProduto5;
    private javax.swing.JTextField txtCodigofornecedorProduto;
    private javax.swing.JTextField txtContatoGarantiaProduto;
    private javax.swing.JTextField txtCorProduto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricaoReduzida;
    private javax.swing.JTextField txtDuracaoGarantiaProduto;
    private javax.swing.JTextField txtLoteProduto;
    private javax.swing.JTextField txtModeloProduto;
    private javax.swing.JTextField txtObservacaoGarantiaProduto;
    private javax.swing.JTextField txtObservacaoProduto;
    private javax.swing.JTextField txtReferenciaProduto;
    private javax.swing.JTextField txtSnProduto;
    private javax.swing.JTextField txtValorProduto;
    // End of variables declaration//GEN-END:variables
}
